# Generated by Django 3.0.5 on 2020-05-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('CityName', models.CharField(max_length=20)),
                ('Img', models.ImageField(upload_to='pics')),
                ('Desc', models.TextField()),
            ],
        ),
    ]
